#' prediction for predict mars
#'
#' Generates predictions from a MARS model object for new data.
#'
#' @param object A MARS model object generated by fitting the model to training data.
#' @param newdata A dataframe containing new observations. The structure of this dataframe
#' should match the original data used to fit the model. If omitted, predictions are made
#' on the training data.
#'
#' @return A vector of predicted values for the newdata based on the MARS model.
#'#' Generates predictions from a MARS model object for new data.
#'
#' @param object A MARS model object generated by fitting the model to training data.
#' @param newdata A dataframe containing new observations. The structure of this dataframe
#' should match the original data used to fit the model. If omitted, predictions are made
#' on the training data.
#'
#' @return A vector of predicted values for the newdata based on the MARS model.
#'
#' @examples
#' # Assuming 'mars_model' is your MARS model object and 'new_data' is your new dataset:
#' # predictions <- predict.mars(mars_model, newdata = new_data)
#'
#' @export
#'
#' @examples
#' # Assuming 'mars_model' is your MARS model object and 'new_data' is your new dataset:
#' # predictions <- predict.mars(mars_model, newdata = new_data)
predict.mars <- function(object,newdata) {
  if(missing(newdata) || is.null(newdata)) {
    B <- as.matrix(object$B)
  }
  else {
    tt <- terms(object$formula,data=newdata)
    tt <- delete.response(tt)
    mf <- model.frame(tt,newdata)
    mt <- attr(mf, "terms")
    X <- model.matrix(mt, mf)[,-1] # remove intercept
    B <- make_B(X,object$Bfuncs)
  }
  beta <- object$coefficients
  drop(B %*% beta)
}

make_B <- function(X, Bfuncs){
  n <- nrow(X)
  Mmax <- length(Bfuncs) - 1
  B <- matrix(1, nrow = n, ncol = Mmax+1) # Recall that B is an N x (Mmax+1) matrix
  for (m in 2:(Mmax+1)){ # Loop through each non-constant basis functions
    s <- Bfuncs[[m]]
    for (i in 1:nrow(s)){ # Loop through each branch (hinge function)
      B[,m] <- B[,m]*h(X[,s[i,"v"]], s[i,"s"], s[i,"t"])  # Update B[,m] using hinge function and new data on covariates.
    }
  }
  # To do: replace ??? with correct values or equations
  return(B)
}

h <- function(x,s,t) {
  return(pmax(0,s*(x-t)))
  # if x>t, s=+1, this return max(0,x-t)
  # if x<t, s=-1, this return max(0,t-x)
}

## ---Test---
#all.equal(predict.mars(testmars,newdata=marstestdata), testpredict)
#all.equal(predict.mars(testmars), testpredict)
